# xterm
[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[colors.normal]
black = "0x000000"
blue = "0x5c5cff"
cyan = "0x00cdcd"
green = "0x00cd00"
magenta = "0xcd00cd"
red = "0xcd0000"
white = "0xe5e5e5"
yellow = "0xcdcd00"

[colors.bright]
black = "0x7f7f7f"
blue = "0x5c5cff"
cyan = "0x00ffff"
green = "0x00ff00"
magenta = "0xff00ff"
red = "0xff0000"
white = "0xffffff"
yellow = "0xffff00"

# Konsole linux
# colors:
#   primary:
#     background: '0x000000'
#     foreground: '0xe3e3e3'
#     bright_foreground: '0xffffff'
#     dim_foreground:    '0xe3e3e3'
# 
#   cursor:
#     text: '0x191622'
#     cursor: '0xf8f8f2'
# 
#   search:
#     matches:
#       foreground: '0xb2b2b2'
#       background: '0xb26818'
#     focused_match:
#       foreground: CellBackground
#       background: CellForeground
# 
#   normal:
#     black:   '0x000000'
#     red:     '0xb21818'
#     green:   '0x18b218'
#     yellow:  '0xb26818'
#     blue:    '0x1818b2'
#     magenta: '0xb218b2'
#     cyan:    '0x18b2b2'
#     white:   '0xb2b2b2'
# 
#   bright:
#     black:   '0x686868'
#     red:     '0xff5454'
#     green:   '0x54ff54'
#     yellow:  '0xffff54'
#     blue:    '0x5454ff'
#     magenta: '0xff54ff'
#     cyan:    '0x54ffff'
#     white:   '0xffffff'
# 
#   dim:
#     black:   '0x000000'
#     red:     '0xb21818'
#     green:   '0x18b218'
#     yellow:  '0xb26818'
#     blue:    '0x1818b2'
#     magenta: '0xb218b2'
#     cyan:    '0x18b2b2'
#     white:   '0xb2b2b2'
