[env]
TERM = "xterm-256color"

[scrolling]
history = 5000

[window]
opacity = 0.85
startup_mode = "Maximized"

[[keyboard.bindings]]
key = "NumpadEnter"
chars = "\r"

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"
